namespace BuildingBlocks.Web.Models;

/// <summary>
/// Standard error response returned by HTTP APIs.
/// Use it from web boundaries when an operation fails before a successful response can be produced.
/// </summary>
/// <param name="Status">HTTP status code for the failed request.</param>
/// <param name="ErrorCode">Stable machine-readable error code.</param>
/// <param name="Message">Client-safe error message.</param>
/// <param name="TraceId">Request trace identifier.</param>
/// <param name="CorrelationId">Optional correlation identifier supplied by the caller or generated by the host.</param>
/// <param name="Errors">General errors that are not tied to a specific input field.</param>
/// <param name="ValidationErrors">Validation errors tied to input fields.</param>
public sealed record ApiErrorResponse(
    int Status,
    string ErrorCode,
    string Message,
    string? TraceId = null,
    string? CorrelationId = null,
    IReadOnlyCollection<ApiError>? Errors = null,
    IReadOnlyCollection<ValidationError>? ValidationErrors = null);
