namespace BuildingBlocks.Web.Models;

/// <summary>
/// Request metadata captured at the HTTP boundary.
/// Use it to pass generic request identifiers without adding business information.
/// </summary>
/// <param name="CorrelationId">Optional correlation identifier supplied by the caller or generated by the host.</param>
/// <param name="TraceId">Request trace identifier.</param>
/// <param name="UserId">Optional authenticated user identifier.</param>
public sealed record RequestContext(string? CorrelationId, string? TraceId, string? UserId);
